######################################## Application ########################################################

appName: notifications-helm
namespace: helm-test

######################################### configmap #########################################################

configmap:
  name: fastapi3-helm-config
                                  ######### mysql ###########                                                           
  mysql:
    user: root
    ip: mysql-istio.app-istio
    port: 3306
    password: 1234
    dbname: notif

########################################## Image ############################################################

image:
  repository: firaschikhaoui/notificationservice
  tag: v1.2